### ISSUE TITLE
Minified Errors

### ISSUE THREAD

**Issue by AleskiWeb** [Credera/angular-bing-maps#39]
When running the `dist/angular-bing-maps.js` through our `gulp-uglify()` in our workflow, we are getting some errors on the front-end. It would seem as if there is a dependency injection error when it is minified.

Also is there a reason the `main:` part of the `bower.json` is pointing to the non-min'd version of the file?

EDIT: Sorry, to clarify, when I use your provided `.min.js` I still get the following error:
    
    UnknownProvider <- e <- bingMapDirective

**Comment by sjmorrow** [comment]
Interesting. Can you provide a stripped down version of your code to help track down the problem?

A few things I would try are:
1. Are you injecting the "angular-bing-maps" dependency into your module definition? See example here: https://github.com/Credera/angular-bing-maps/blob/develop/example/bing-map-directive.html#L10
2. If you are minifying angular code, are you either using the [inline array annotation](https://docs.angularjs.org/guide/di#inline-array-annotation) for dependency injection, or using a third-party tool like [ng-annotate](https://github.com/olov/ng-annotate)? If you are not doing one or the other, it might cause your problem.

To answer your other question, the reason that we are using the non-minified version in the main: declaration of `bower.json` is because most people who use the main: declaration to pull in dependencies are also using their own minification step, as you are doing with `gulp-uglify()`. This makes it easier for users to debug any problems with our library during development.

**Comment by AleskiWeb** [comment]
I believe we are. SO we have the following in the parent module:

    .module('app-map',
    [
        //Angular-Bing-Maps component
        'angularBingMaps'
    ]);

After that I have been asuming I can use anything under this module (`app-map`) to call directives that are in `angularBingMaps`. So for example if I have a `MapController` like so:

    MapController = function () {
        var self = this;
        self.authKey = 'dasdajdiajdiajsdoajdioasdj';
    };

    Module.controller('MapController', []);

I would then, in a view called directly under this `MapController` be able to use:

    <bing-map credentials='m.authKey'></bing-map>

Have I missed something I need to annotate and inject inside of the `MapController`?

**Comment by sjmorrow** [comment]
@AleskiWeb I have confirmed there is indeed an issue with the minified version of the compiled source. I am looking into it now. All I have discovered so far is that the code that defines the directives is never being run. Unfortunately, debugging minified code is worse than looking for a needle in a haystack, so I suggest using the non-minified version in the meantime since you are running it through your own uglification anyways.

**Comment by sjmorrow** [comment]
Alright, that should do it. I also pushed a bugfix release (v0.2.1) so that other users will not experience this same problem. Thanks for finding that.

**Comment by AleskiWeb** [comment]
@sjmorrow I might be missing something but this still isnt working for myself, I am getting the same error as previously.

Not sure if its an issue but your bower tells me that im still getting 0.2.0 (in the bower json, if I change this to 0.2.1 then it tells me there is a version mismatch and continues to just get 0.2.0)

I can confirm that I am *actually* getting the new change, but it would seem that it isnt working for me at all now, whether I minify or not.

**Comment by sjmorrow** [comment]
@AleskiWeb Sorry, that was probably my fault for not bumping the version number in bower.json. I just fixed that and updated the tag to match. Can you try doing a `bower cache clean` and then running `bower install angular-bing-maps#0.2.1` on your project and seeing if you still get the same error?

**Comment by AleskiWeb** [comment]
![2015-10-01_16-20-44](https://cloud.githubusercontent.com/assets/8318899/10224991/95a20d40-6858-11e5-989c-a84e6189cc89.png)

I can see the code from the module in my concatenated dependencies file, but it still is looking for something that doesn't ever appear `bingMapDirective`. Is the annotation correct? I can find the directive `bingMap` just not `bingMapDirective`.

The following is in my min file:

    angular.module("angularBingMaps.directives").directive("bingMap",a)

It's strang that its still saying it can't find `bingMapDirective` when it should have been renamed to look for `a` right?

**Comment by sjmorrow** [comment]
That's not really strange. I believe that is as expected. The directive name is still "bingMap" as seen in your code snippet above. the `a` is just a mangled function name, which should have no effect on what directive angular looks for. Angular sees the directive name ("bingMap") and uses that to look for "bingMapDirective" (which it has defined internally, so don't worry that you don't see that in the code). So the only strange thing here is that it appears the directive is never instantiated. I'm betting if you managed to set a breakpoint on that line you pasted above, it would never get hit. That is the same problem I was seeing before the fix I made. I'll try and do a little more digging on why the mangling of function names is causing the directives to not be instantiated.

Can you try to disable mangling on your uglication process to see if that makes it start working?

**Comment by AleskiWeb** [comment]
It works, yes, if `mangle` is set to `false`.

**Comment by AleskiWeb** [comment]
I'm not sure if this is being looked into? Should we move this back to an open issue?

**Comment by ceo-mint-soft** [comment]
i got same error..
